### ISSUE TITLE
Necesitamos una imagen

### ISSUE THREAD

**Issue by danielacos** [BoletinSEMA/Boletin20#3]
La imagen del logotipo SEMA en naranja de la sección 5 del boletín 20 (A un año del ICIAM 2019) no se encuentra en la carpeta figuras. He mirado el código HTML y hace referencia a la carpeta figuras del boletín 19.

**Comment by rrgalvan** [comment]
He subido la imagen al directorio html/img/

Se me ocurre que no siempre tenemos por qué incluir en nuestros repositorios las imágenes que estén en internet. Podemos enlazar a imágenes que estén en internet (siempre que confiemos que sigan estando en el futuro). Por ejemplo, en este caso, en vez de;

img src="../Boletin-N19-mayo2018/figuras/iciam2019-naranja.jpg"

podríamos haber escrito: 

img src="https://www.sema.org.es/images/boletines/boletin21/21/figuras/iciam2019-naranja.jpg"

Esta última dirección web la he encontrado buscando en google "iciam2019-naranja"
