### ISSUE TITLE
Revisión de vuestros datos

### ISSUE THREAD

**Issue by rrgalvan** [BoletinSEMA/Boletin20#4]
He incluído (a pie de página) vuestro nombre como colaboradores del Boletín20, https://boletinsema.github.io/Boletin20/html/index.html

Os he puesto por orden alfabético. Lo siento si es un poco injusto, yo soy Rodriguez y siempre me toca al final :)

Por favor, ¿podéis revisar que todo sea correcto? Si queréis corregir algo, lo podéis hacer vosotros mismos

**Comment by Juanan7676** [comment]
Mis datos están correctos

**Comment by NoeliaOrtega** [comment]
Los míos están correctos también

**Comment by danielacos** [comment]
Los míos también están bien.

**Comment by GloriaAlmozara** [comment]
Mis datos están correctos.

**Comment by AlbaNaIz** [comment]
Mis datos también están correctos
